# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 165)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.inputvalidacpf = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inputvalidacpf.setFont(font)
        self.inputvalidacpf.setObjectName("inputvalidacpf")
        self.gridLayout.addWidget(self.inputvalidacpf, 0, 1, 1, 1)
        self.btnvalidacpf = QtWidgets.QPushButton(self.centralwidget)
        self.btnvalidacpf.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnvalidacpf.setFont(font)
        self.btnvalidacpf.setStyleSheet("")
        self.btnvalidacpf.setObjectName("btnvalidacpf")
        self.gridLayout.addWidget(self.btnvalidacpf, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.btngeracpf = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btngeracpf.setFont(font)
        self.btngeracpf.setObjectName("btngeracpf")
        self.gridLayout.addWidget(self.btngeracpf, 1, 2, 1, 1)
        self.labelretorno = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.labelretorno.setFont(font)
        self.labelretorno.setStyleSheet("color: green")
        self.labelretorno.setText("")
        self.labelretorno.setAlignment(QtCore.Qt.AlignCenter)
        self.labelretorno.setObjectName("labelretorno")
        self.gridLayout.addWidget(self.labelretorno, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Valida ou Gera CPF"))
        self.label_2.setText(_translate("MainWindow", "Validar CPF"))
        self.btnvalidacpf.setText(_translate("MainWindow", "VALIDAR"))
        self.label.setText(_translate("MainWindow", "GERA CPF:"))
        self.btngeracpf.setText(_translate("MainWindow", "GERAR"))
